on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-cross:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/cli"
        binary_name: "setlist-to-playlist"
        build_flags: "-trimpath"
        ldflags: "-w -s -buildid="
